### ISSUE TITLE
Turning in Healer quest crashes the app

### ISSUE THREAD

**Issue by brian-gates** [brian-gates/adventure-bot#54]
```
E:\adventure-bot\adventure-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:89
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (E:\adventure-bot\adventure-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:89:46)
    at Client.<anonymous> (E:\adventure-bot\adventure-bot\.build\index.js:76:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}
error Command failed with exit code 1.
```

**Comment by brian-gates** [comment]
https://github.com/brian-gates/adventure-bot/commit/7f2b0ef46a5d8fef0c9b8fbba7f19a501a6a8832
